### ISSUE TITLE
Error while compiling with gcc 5.5

### ISSUE THREAD

**Issue by pramodk** [HPCToolkit/hpctoolkit-externals#1] opened 2018-03-21 13:48 UTC
I am seeing following error (which is obvious):

```
ml2-2.6.32/debugXML.c  -fPIC -DPIC -o .libs/debugXML.o
../libxml2-2.6.32/debugXML.c: In function 'xmlCtxtDumpSpaces':
../libxml2-2.6.32/debugXML.c:144:35: error: format not a string literal and no format arguments [-Werror=format-security]
             fprintf(ctxt->output, &ctxt->shift[100 - 2 * ctxt->depth]);
                                   ^
../libxml2-2.6.32/debugXML.c:146:35: error: format not a string literal and no format arguments [-Werror=format-security]
             fprintf(ctxt->output, ctxt->shift);
                                   ^
cc1: some warnings being treated as errors
```

I tried to specify CFLAGS (-Wno-format-security) but it seems like that doesn't get *appended*:

```
gcc -DHAVE_CONFIG_H -I. -I../libxml2-2.6.32 -I./include -I../libxml2-2.6.32/include -D_REENTRANT -Wno-format-security -pedantic -W -Wformat -Wunused -Wimplicit -Wreturn-type -Wswitch -Wcomment -Wtrigraphs -Wformat -Wchar-subscripts -Wuninitialized -Wparentheses -Wshadow -Wpointer-arith -Wcast-align -Wwrite-strings -Waggregate-return -Wstrict-prototypes -Wmissing-prototypes -Wnested-externs -Winline -Wredundant-decls -MT debugXML.lo -MD -MP -MF .deps/debugXML.Tpo -c ../libxml2-2.6.32/debugXML.c  -fPIC -DPIC -o .libs/debugXML.o
```

**Comment by mwkrentel** [comment] 2018-04-09 18:21
First, I'd prefer sending issues to the hpctoolkit page, not here.
Yeah, I know the failure is in externals, but I wasn't expecting
anything to show up here and I never look here.  But if you really
want to get someone's attention, send mail to hpctoolkit-forum.

Anyway, this one is easy.  We don't use libxml anymore, haven't for
years.  I've now turned the default for libxml to not build, so I'll
close this issue.

Btw, I was unable to reproduce your failure.  I've built libxml with
gcc 4.8, 5.4.0, 6.x, 7.x on x86 and powerpc and it works for me.
But it's not worth tracking down.

**Closed as completed** 2018-04-09 18:21 UTC
